### ISSUE TITLE
mServerUrl regex for hosts with subdirectories

### ISSUE THREAD

**Issue by STFBEE** [Navigine/Android-SDK#22]
Hello
I'm have an issue with using your library with our local backend, which endpoint is located at `http://example.com/example` and we can't change it soon. Can you change the regex in `NavigineSDK.initialize()` so that it allows urls with subdirectories in next release?

**Comment by PavelTychinin** [comment]
Hello!
We know about it. It will be fixed next release.
Thanks!

**Comment by STFBEE** [comment]
Great
How long does it take before it goes into production?

**Comment by PavelTychinin** [comment]
About a week
