### ISSUE TITLE
NavigineDemo (self-built APK from master branch) fails to load 'Navigine Demo' location

### ISSUE THREAD

**Issue by S-trace** [Navigine/Android-SDK#30]
Hello.

The error message is:
"Error downloading location 'Navigine Demo' (error -403)! Please, try again later or contact technical support"

What should i do to make it work?

Thank you.

**Comment by MrCrambo** [comment]
Hi there. This error means that you do not have permissions to this location.
You can test the demo using this user hash - "F062-5F1A-E8A2-296B" with the same location name. But we highly recommend you to create your own location and to test on it!
