### ISSUE TITLE
Is this source code correspond to the navigine demo apk available in play store?

### ISSUE THREAD

**Issue by jasirjasir** [Navigine/Android-SDK#36]
Is this source code correspond to the demo apk available in play store?
[](https://play.google.com/store/apps/details?id=com.navigine.navigine)
 As per the navigine doc, source code for demo apk is available in  []( https://github.com/Navigine/Android-SDK/tree/master/Navigine) . But code is missing in this link

**Comment by MrCrambo** [comment]
Hey, @jasirjasir 

This is not the source code for the application in Play Market. This is the source code for Demo application, that you can build yourself by changing the credentials. If you wrote about [this docs](https://docs.navigine.com/ud_android_demo.html), all the links are correct.
