### ISSUE TITLE
Further Explanation from previous issue

### ISSUE THREAD

**Issue by Naiqiew** [Navigine/Android-SDK#38]
Hi, I am a student using your Navigine SDK for my school project. Regarding issue 37, could you explain a bit more about the map being finite? Thanks.

**Comment by MrCrambo** [comment]
Hey, @Naiqiew

That means, that our map is limited(restricted) in horizontal and vertical orientations, so there could appear some collisions when you will rotate it, like getting stuck in corners, going out of map size, etc.

So for avoiding this issues we do not support rotation, by the way, if you want to show your device orientation, you could use [DeviceInfo class](https://github.com/Navigine/Android-SDK/wiki/Class-DeviceInfo) and example at the bottom of the page!

**Comment by Naiqiew** [comment]
I see, thank you!
