### ISSUE TITLE
Question on Zone Notification

### ISSUE THREAD

**Issue by Naiqiew** [Navigine/Android-SDK#39]
Hi, I am a student using NavigineSDK for my school project. Is it possible to include a vibrate option for the zone notification? Thanks

**Comment by MrCrambo** [comment]
Hey, @Naiqiew 

Our SDK provides only the listener for entering / leaving zones, building notifications is on the user side, so you can find more information in [this link](https://developer.android.com/training/notify-user/build-notification) about building notifications and turning on vibration.

Hope it will help you!
