### ISSUE TITLE
Loading JNI: failed

### ISSUE THREAD

**Issue by Mehta2015** [Navigine/Android-SDK#4]
when I try to run sample application, I am facing below error:
"File /libs/armeabi/libnavigate-jni.so was not found inside JAR."
How can I resolve this error? due to this error, I am not able check sample application.

Thanks

**Comment by fedormex** [comment]
It seems that your device architecture is not supported by the Navigine SDK.
1. What device are you using?
2. Are you using our APK or trying to rebuild application yourself from the sources?

**Comment by Mehta2015** [comment]
I have tested Your pre-compiled apk as well as try to run sample application which come along with Navigine SDK in Sony Xperia C2 and Sony Xperia M2. But in both ways I got same error like: "libnavigate-jni.so  was not found inside JAR".

**Comment by FRIST008** [comment]
Hey, Android studio not compiled *.so from Navigine_SDK.jar.
I copy *.so files from Navigine_SDK.jar and paste in folder ../app/libs/ and added in build.gradle 

`sourceSets {
		main {
			jniLibs.srcDirs = ['libs']
		}
	}`

But after compilation the files *.so was moved in folder 'lib'. See apk:
![a7a09aeebf](https://cloud.githubusercontent.com/assets/8448423/17440867/275e2904-5b37-11e6-8b40-b5b21510b09a.png)

You searching *.so files in 'libs'. See 159 row in NavigationThread.class.

Please fix and add *.so files on repository.

**Comment by fedormex** [comment]
It seems that you were using incorrect version of Navigine_SDK.jar.
Please try a new version 4.0.4 (that i have committed). Files *.so are replaced from archive and should be removed from build.gradle.

**Comment by FRIST008** [comment]
4.0.4 is worked for me! Thanks
