### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by edifier852** [Navigine/Android-SDK#5]
I connected sdk in my project and when try to create new NavigationThread I get an exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/ru.apps.app/files/libnavigate-jni.so" is 32-bit instead of 64-bit. 
Demo app works fine on this phone.
How can I resolve it?

**Comment by fedormex** [comment]
We have added support for x86_64 arch in Navigine_SDK.jar.
Could you try to rebuild your application with a new Navigine_SDK.jar?

**Comment by edifier852** [comment]
After update SDK I have exception
java.io.FileNotFoundException: File /libs/armeabi/libnavigate-jni.so was not found inside JAR.

**Comment by edifier852** [comment]
After update SDK I have exception
java.io.FileNotFoundException: File /libs/armeabi/libnavigate-jni.so was
not found inside JAR.

2016-01-20 13:21 GMT+02:00 Fedor Puchkov <notifications@github.com>:
