### ISSUE TITLE
运行打开出问题

### ISSUE THREAD

**Issue by HenryLQH** [Navigine/Android-SDK#9]
The NavigineDemo runs "You are out of navigation zone! Please,check that your bluetooth is enabled! . I turned on the bluetooth and it is useless. How do you solve this problem?

**Comment by AlexeyPanyov** [comment]
HenryLQH, you need to add iBeacons to your map first. After that you will see yourself on the map.

**Comment by madwols** [comment]
The problem is how to change the map in the demo ?
